---
name: "tagged-release-earthly"

#on:
#  push:
#    tags:
#      - "v*"
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build binaries"
    runs-on: "ubuntu-latest"
    env:
      FORCE_COLOR: 1

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Cache build result
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./dist_build/
          key: ${{ runner.os }}-dist_build-${{ github.sha }}
      - name: Download latest earthly
        run: |
          wget https://github.com/earthly/earthly/releases/download/v0.5.20/earthly-linux-amd64 \
            -O /tmp/earthly && chmod +x /tmp/earthly
      -
        name: "Build"
        run: /tmp/earthly +build
#        env:
#          BUILD_DIR: /tmp/build_root/issuemon

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs:
      - build
    #env:
      #DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            ./dist_build/bin/issuelist
            ./dist_build/bin/grouplist
